export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

// user
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
